#!/bin/dash

#Copyright (c) 2014 Luigi Tarenga <luigi.tarenga@gmail.com>
#Distributed under the terms of a MIT license.

cd $(dirname $0)
read lock_path < conf/lock_path
PATH=:$lock_path:$PATH
if [ ! -x  $lock_path/get-lock ] ; then
   echo "back-to-work need dex-lock to run. install it and configure its location."
   exit 1
fi

package=$1
if [ -z "$package" ] ; then
   echo "Usage: ${0##*/} { package-name}"
   echo "  This is the cluster package monitor. It can run on multiple node and only"
   echo "  one instance switch from stand-by to active state to start the package"
   echo "  services. The active one will poll and monitor the health of the package"
   echo "  and in case of failure will shutdown it letting another monitor to try"
   echo "  to start it again on another node."
   echo "  Usually it's started with the \"service start <packag-name>\" command."
   exit 0
fi

pace=$(packages/$package echo pace)
timeout=$(packages/$package echo timeout)
timeout2=$(packages/$package echo stop_timeout)
role="stand-by"
stop="false"

if ! mkdir temp/monitor_lockdir_$package 2> /dev/null ; then
   echo "temp/monitor_lockdir_$1 already exist. back-to-work is already running for package $1."
   exit 1
fi

init-lock $package $timeout $timeout2

#do not immidiately exit on kill! we must stop the package before quitting!
trap 'echo "$(date) received signal SIGHUP. starting halt sequence." ; stop="true"' HUP
trap 'echo "$(date) received signal SIGINT. starting halt sequence." ; stop="true"' INT
trap 'echo "$(date) received signal SIGTERM. starting halt sequence." ; stop="true"' TERM

quit () {
   rmdir temp/monitor_lockdir_$package
   release-lock $package
   exit $1
}

echo "$(date) starting as stand-by node." & sleep_pid=$!
while true ; do
   wait $sleep_pid ; sleep $pace & sleep_pid=$!
   case $role in
    stand-by)
      [ "$stop" = "true" ] && quit 0
      if get-lock $package $timeout $timeout2 $pace ; then
         echo "$(date) got lock. switch to active node."
         start_timeout=$(packages/$package echo start_timeout)
         stop_timeout=$(packages/$package echo stop_timeout)
         pkg_state="unknown"
         role="active"
      fi
    ;;

    active)
      if ! get-lock $package $timeout $timeout2 $pace ; then
         echo "$(date) lock lost. shutting down."
         stop="true"
      fi

      old_state=$pkg_state
      #handle all cases of the package state machine
      case $pkg_state in
       starting)
         if ! pkill -0 -x -f "$shell_cmd packages/$package start" ; then
            wait $start_pid
            if [ $? -eq 0 ] ; then
               pkg_state="running"
            else
               pkg_state="failing"
            fi
         else
            start_timeout=$(($start_timeout-$pace))
         fi

         if [ $start_timeout -le 0 ] ; then
            echo "$(date) timeout waiting for package to start."
            pkill -x -f "$shell_cmd packages/$package start"
            packages/$package stop >> log/$package.log &
            stop_pid=$!
            pkg_state="failing"
         fi
       ;;

       running)
         #status function returns: 0 up, 1 down, 2 degraded
         packages/$package status >> log/$package.log 
         pkg_status=$?
         if [ "$stop" = "true" ] ; then
            packages/$package stop >> log/$package.log &
            pkg_state="halting"
         elif [ $pkg_status -ne 0 ] ; then
            packages/$package stop >> log/$package.log &
            pkg_state="failing"
         fi
       ;;

       halting|failing)
         if ! pkill -0 -x -f "$shell_cmd packages/$package stop" ; then
            wait $stop_pid
            if [ $? -eq 0 ] ; then
               [ "$pkg_state" = "halting" ] && pkg_state="halted"
               [ "$pkg_state" = "failing" ] && pkg_state="failed"
            else
               pkg_state="failed"
            fi
         else
            stop_timeout=$(($stop_timeout-$pace))
         fi

         if [ $stop_timeout -le 0 ] ; then
            echo "$(date) timeout waiting for package to stop."
            #pkill -x -f "$shell_cmd packages/$package stop"
            pkg_state="failed"
         fi
       ;;

       halted|failed)
            if [ "$pkg_state" = "halted" ] ; then
               echo "$(date) package $pkg_state. exit."
               quit 0
            fi
            echo "$(date) package $pkg_state. restarting as stand-by."
            release-lock $package $timeout $timeout2
            sleep $pace
            role="stand-by"
       ;;

       unknown)
         shell_cmd=$(head -1 packages/$package)
         shell_cmd=${shell_cmd#\#!}

         if pkill -0 -x -f "$shell_cmd packages/$package start" ; then
            echo "$(date) start script already running. package state is unknown."
            quit 1
         fi

         if pkill -0 -x -f "$shell_cmd packages/$package stop" ; then
            echo "$(date) stop script already running. package state is unknown."
            quit 1
         fi

         packages/$package status >> log/$package.log 
         pkg_status=$?
         if [ "$stop" = "false" -a $pkg_status -eq 1 ] ; then
            packages/$package start >> log/$package.log &
            start_pid=$!
            pkg_state="starting"
         else
            packages/$package stop >> log/$package.log &
            stop_pid=$!
            pkg_state="failing"
         fi 
       ;;
      esac # package_state

      if [ "$old_state" != "$pkg_state" ] ; then
         echo "$(date) package state changes to $pkg_state."
      fi
    ;;
   esac # role
done
