#!/bin/dash

pace=4
timeout=12
start_timeout=4
stop_timeout=10

case $1 in
 start)
   touch /tmp/$(basename $0).started
   exit 0
 ;;

 stop)
   rm /tmp/$(basename $0).started
 ;;

 status)
   num_check=1
   failed_check=1

   # can return 3 values: 0 up, 1 down, 2 degraded
   if [ -f /tmp/$(basename $0).started ] ; then
      failed_check=$(($failed_check-1))
   fi

   [ "$failed_check" -eq "$num_check" ] && exit 1
   [ "$failed_check" -eq "0" ] && exit 0
   exit 2
 ;;

 echo)
   eval echo \$$2
 ;;
esac
