#!/bin/sh

# start of configuration section

pace=4
timeout=20
ip_0=192.168.68.68; prefix_0=24; netmask_0=255.255.255.0; network_0=192.168.68.0; netdev_0=eth0
ip_1=192.168.68.69; prefix_1=24; netmask_1=255.255.255.0; network_1=192.168.68.0; netdev_1=eth0
start_timeout=10
stop_timeout=10

# end of configuration section

cd $(dirname $0)

### start of include functions section #######################

if [ -f functions/network.$(uname) ] ; then
   . functions/network.$(uname)
else
   echo "Operating system not supported for network functions"
   exit 1
fi

#
# include other functions if package needs them
#

### do not include functions below this line ##################

case $1 in
 echo)
   eval echo \$$2
 ;;
 status)
   num_check=${num_check:-0}
   failed_check=${failed_check:-0}
   #by default if num_check=0 you will exit with 1. package is down.
   [ "$failed_check" -eq "$num_check" ] && exit 1
   [ "$failed_check" -eq "0" ] && exit 0
   exit 2
 ;;
esac
